-- MySQL Script generated by MySQL Workbench
-- Tue May 14 22:59:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peliculas-tap
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `peliculas-tap` ;

-- -----------------------------------------------------
-- Schema peliculas-tap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peliculas-tap` DEFAULT CHARACTER SET utf8 ;
USE `peliculas-tap` ;

-- -----------------------------------------------------
-- Table `peliculas-tap`.`peliculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculas-tap`.`peliculas` ;

CREATE TABLE IF NOT EXISTS `peliculas-tap`.`peliculas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dateLaunch` DATE NOT NULL,
  `director` VARCHAR(45) NULL,
  `category` CHAR(1) NULL,
  `duration` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
